# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:bremor/animations/carpenter_carry_plank/zzz/apply_frame {frame: 16}
scoreboard players add @s aj.carpenter_carry_plank.frame 1