# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.happy_mask_salesman.animation.happy_mask_idle_heavy.playing
tag @s remove aj.happy_mask_salesman.animation.happy_mask_introduction_1.playing
tag @s remove aj.happy_mask_salesman.animation.happy_mask_introduction_2.playing
tag @s remove aj.happy_mask_salesman.animation.happy_mask_introduction_3_6_8.playing
tag @s remove aj.happy_mask_salesman.animation.happy_mask_introduction_4.playing
tag @s remove aj.happy_mask_salesman.animation.happy_mask_introduction_5.playing
tag @s remove aj.happy_mask_salesman.animation.happy_mask_introduction_7.playing