# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/pause_all
tag @s add aj.tingle.animation.bomber_shoot.playing
scoreboard players set @s aj.bomber_shoot.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:tingle/animations/bomber_shoot/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only