# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:jugglers rig_hash set value 'f8e6058e3bd905d5257b5a992ba28ae98e64bcc13787197f1380784822fdb1b9'
scoreboard objectives add aj.jugglers_idle.frame dummy