# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:north_gate_soldier/animations/guard_idle/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.guard_idle.frame 1