# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lowerrightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5625f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerleftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5625f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_tingle_pen) {transformation: [-0.75f,0f,0f,-0.1875f,0f,0f,-0.75f,1.5938f,0f,-1.5f,0f,0.2813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.5f,0f,0f,-0.5625f,0f,1.5f,0f,2.0625f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_tingle_book) {transformation: [-0.5303f,0f,-0.5303f,0.4688f,-0.5303f,0f,0.5303f,1.125f,0f,0.75f,0f,0.4688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,1.5f,0f,2.0625f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.25f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_tingles_pack) {transformation: [-0.75f,0f,0f,0f,0f,0.75f,0f,1.875f,0f,0f,-0.375f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_tingles_ballon_small) {transformation: [-1.515f,0f,0f,0f,0f,-1.312f,0.7575f,3.0938f,0f,0.7575f,1.312f,-0.9375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_tingles_ballon_big) {transformation: [-3f,0f,0f,0f,0f,-2.1109f,1.5f,4.125f,0f,1.2187f,2.5981f,-1.5469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"sounds":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}