# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/tingle_idle/zzz/apply_frame {frame: 18}
scoreboard players add @s aj.tingle_idle.frame 1