# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:brac/animations/carpenter_shout/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.carpenter_shout.frame 1