# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.south_gate_soldier.animation.banker_idle.playing
tag @s remove aj.south_gate_soldier.animation.banker_wave.playing
tag @s remove aj.south_gate_soldier.animation.banker_pound.playing
tag @s remove aj.south_gate_soldier.animation.banker_dance.playing
tag @s remove aj.south_gate_soldier.animation.default.playing
tag @s remove aj.south_gate_soldier.animation.soldier_idle.playing
tag @s remove aj.south_gate_soldier.animation.soldier_block.playing
tag @s remove aj.south_gate_soldier.animation.soldier_move.playing