# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'ee9ad9cf56c7f63f94a7689a04c7135e61c534e59fc8517c5e4a549e2390f7bb'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack