# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '6f3ee83be75fbb62ca0569ba86b235ec90821fd329728edf87690ba77f72c298'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack