# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f7685ce8a2425db20e0a0111fc2e5f8cb0ce1282b10e05a3290874150de6e4de'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack