# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.greatfairy_clocktown.root] run return 0
execute if entity @s[tag=aj.greatfairy_clocktown.animation.greatfairy_appear.playing] run function animated_java:greatfairy_clocktown/animations/greatfairy_appear/zzz/on_tick
execute if entity @s[tag=aj.greatfairy_clocktown.animation.greatfairy_appear2float.playing] run function animated_java:greatfairy_clocktown/animations/greatfairy_appear2float/zzz/on_tick
execute if entity @s[tag=aj.greatfairy_clocktown.animation.greatfairy_float.playing] run function animated_java:greatfairy_clocktown/animations/greatfairy_float/zzz/on_tick
execute if entity @s[tag=aj.greatfairy_clocktown.animation.greatfairy_float2reach.playing] run function animated_java:greatfairy_clocktown/animations/greatfairy_float2reach/zzz/on_tick
execute if entity @s[tag=aj.greatfairy_clocktown.animation.greatfairy_reach.playing] run function animated_java:greatfairy_clocktown/animations/greatfairy_reach/zzz/on_tick
execute if entity @s[tag=aj.greatfairy_clocktown.animation.greatfairy_reach2float.playing] run function animated_java:greatfairy_clocktown/animations/greatfairy_reach2float/zzz/on_tick
execute if entity @s[tag=aj.greatfairy_clocktown.animation.greatfairy_float2disappear.playing] run function animated_java:greatfairy_clocktown/animations/greatfairy_float2disappear/zzz/on_tick
execute if entity @s[tag=aj.greatfairy_clocktown.animation.greatfairy_disappear.playing] run function animated_java:greatfairy_clocktown/animations/greatfairy_disappear/zzz/on_tick
execute on passengers run rotate @s ~ ~