# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'ccd98c4ff01bce48a3221ebfe915687adb53dfe91aa4f3b6d0164e5c70888643'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack