# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'd5c17daad17bca620d4c098a70cb8dde9eaae65bf8b5a70f0b82cceeadd257bf'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack