# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.west_gate_soldier.animation.guard_idle.playing
tag @s remove aj.west_gate_soldier.animation.guard_idle_day3.playing
tag @s remove aj.west_gate_soldier.animation.guard_block.playing
tag @s remove aj.west_gate_soldier.animation.guard_move.playing