# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:brac rig_hash set value '104676471561657ab471b607b88d6dee69ccbd8923a2ee2233a64ffdfd9aef60'
scoreboard objectives add aj.banker_idle.frame dummy
scoreboard objectives add aj.banker_wave.frame dummy
scoreboard objectives add aj.banker_pound.frame dummy
scoreboard objectives add aj.banker_dance.frame dummy
scoreboard objectives add aj.default.frame dummy
scoreboard objectives add aj.apprentice_stare_up.frame dummy
scoreboard objectives add aj.carpenter_wave_up.frame dummy
scoreboard objectives add aj.carpenter_shout_up.frame dummy
scoreboard objectives add aj.carpenter_idle.frame dummy
scoreboard objectives add aj.guard_idle.frame dummy
scoreboard objectives add aj.guard_block.frame dummy
scoreboard objectives add aj.guard_move.frame dummy