# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:brac rig_hash set value '34fc3f75f6bed00640cefe745ddf1f0308de9245d41ef528f660e97052a77eca'
scoreboard objectives add aj.carpenter_shout.frame dummy