# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/guard_block/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.guard_block.frame 1