# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.stray_fairy_clocktown.root] run return 0
execute if entity @s[tag=aj.stray_fairy_clocktown.animation.idle.playing] run function animated_java:stray_fairy_clocktown/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.stray_fairy_clocktown.animation.move.playing] run function animated_java:stray_fairy_clocktown/animations/move/zzz/on_tick
execute if entity @s[tag=aj.stray_fairy_clocktown.animation.collected.playing] run function animated_java:stray_fairy_clocktown/animations/collected/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:stray_fairy_clocktown/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~