# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/bomber_walk/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.bomber_walk.frame 1