# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.banker.animation.default.playing
tag @s remove aj.banker.animation.idle.playing
tag @s remove aj.banker.animation.wave.playing
tag @s remove aj.banker.animation.pound.playing
tag @s remove aj.banker.animation.dance.playing