# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:bremor rig_hash set value '0885d5f9a21b56da22444ec5cbf265d3389c6e2ed014c3de222e004c70db243e'
scoreboard objectives add aj.carpenter_carry_plank.frame dummy