# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:bremor rig_hash set value 'd7537bbf021c34b7ea51b1aa29d613f4955c9179187df5d68f82d5d691dcf7e4'
scoreboard objectives add aj.banker_idle.frame dummy
scoreboard objectives add aj.banker_wave.frame dummy
scoreboard objectives add aj.banker_pound.frame dummy
scoreboard objectives add aj.banker_dance.frame dummy
scoreboard objectives add aj.default.frame dummy
scoreboard objectives add aj.apprentice_stare_up.frame dummy
scoreboard objectives add aj.carpenter_wave_up.frame dummy
scoreboard objectives add aj.carpenter_shout_up.frame dummy
scoreboard objectives add aj.carpenter_idle.frame dummy
scoreboard objectives add aj.guard_idle.frame dummy
scoreboard objectives add aj.guard_block.frame dummy
scoreboard objectives add aj.guard_move.frame dummy
scoreboard objectives add aj.carpenter_carry_plank.frame dummy