# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '104676471561657ab471b607b88d6dee69ccbd8923a2ee2233a64ffdfd9aef60'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack