# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '34fc3f75f6bed00640cefe745ddf1f0308de9245d41ef528f660e97052a77eca'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack