# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.chest_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_chest_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.lowerrightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerrightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.upperrightleg_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_upperrightleg_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.rightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.lowerleftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerleftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.upperleftleg_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_upperleftleg_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.leftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.rightarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.leftarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.pack] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_pack set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.happy_mask_salesman.node.torso] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso set from storage animated_java:gu out