# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.lowerrightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerrightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.rightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.lowerleftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerleftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.leftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.plank] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_plank set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.rightarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.leftarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.head_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.bremor.node.torso] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso set from storage animated_java:gu out