# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lowerrightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,0f,1.5f,0.1648f,0f,1.5f,0f,0.3977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.0607f,-1.0607f,0.5625f,0f,-1.0607f,-1.0607f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerleftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,0f,1.5f,0.1648f,0f,1.5f,0f,0.3977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.0607f,-1.0607f,0.5625f,0f,-1.0607f,-1.0607f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_plank) {transformation: [-0.375f,0f,0f,-0.1875f,0f,-4.3467f,-0.0971f,1.2982f,0f,-1.1647f,0.3622f,0.8765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.5f,0f,0f,-0.5625f,0f,0.3882f,-1.4489f,1.4681f,0f,-1.4489f,-0.3882f,0.2426f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.3882f,-1.4489f,1.4681f,0f,-1.4489f,-0.3882f,0.2426f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head_layer2) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,1.6492f,0f,0f,-1.5f,0.2912f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,1.6492f,0f,0f,-1.5f,0.2912f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4489f,0.3882f,0.5625f,0f,0.3882f,-1.4489f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}