# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '4ee88d8158cf21934e4fc2df2f708ea55528b06ae0df02d54f279c44724b540e'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack