# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b17cc4d389154f5e0635f3e950d0bf505dcc3a10f8b7a28b46ec8ac8ed248bef'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack