# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:brac/animations/pause_all
tag @s add aj.brac.animation.carpenter_shout_up.playing
scoreboard players set @s aj.carpenter_shout_up.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:brac/animations/carpenter_shout_up/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only