# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.chest_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_chest_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.lowerrightleg_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerrightleg_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.lowerrightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerrightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.upperrightleg_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_upperrightleg_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.rightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.lowerleftleg_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerleftleg_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.lowerleftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerleftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.upperleftleg_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_upperleftleg_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.leftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.rightarm_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightarm_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.rightarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.leftarm_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftarm_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.leftarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.head_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.left_tip] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_tip set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.left_end] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_end set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.left_mid] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_mid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.left_base] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_base set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.middle_tip] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_middle_tip set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.middle_end] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_middle_end set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.middle_mid] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_middle_mid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.middle_base] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_middle_base set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.right_tip] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_tip set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.right_end] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_end set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.right_mid] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_mid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.right_base] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_base set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.greatfairy_clocktown.node.torso] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso set from storage animated_java:gu out