# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:apprentice/animations/pause_all
tag @s add aj.apprentice.animation.carpenter_wave_up.playing
scoreboard players set @s aj.carpenter_wave_up.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:apprentice/animations/carpenter_wave_up/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only