# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1f,0f,0f,-0.125f,0f,0f,1f,0.1098f,0f,1f,0f,0.2652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1f,0f,0f,-0.125f,0f,0.7071f,-0.7071f,0.375f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1f,0f,0f,0.125f,0f,0f,1f,0.1098f,0f,1f,0f,0.2652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1f,0f,0f,0.125f,0f,0.7071f,-0.7071f,0.375f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [-0.1855f,0.1805f,0.9659f,-0.1725f,0.8594f,0.5065f,0.0704f,0.4385f,-0.4765f,0.8432f,-0.2491f,0.3015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9659f,-0.1855f,-0.1805f,-0.375f,-0.0704f,0.8594f,-0.5065f,0.9764f,0.2491f,-0.4765f,-0.8432f,0.17f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9659f,0.1855f,0.1805f,0.375f,0.0704f,0.8594f,-0.5065f,0.9764f,-0.2491f,-0.4765f,-0.8432f,0.17f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.0967f,0f,0f,-1f,0.204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.0967f,0f,0f,-1f,0.204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1f,0f,0f,0f,0f,0.9623f,0.272f,0.375f,0f,0.272f,-0.9623f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":2.4979611909681373e-17,"py":-0.34673028413041673,"pz":-0.20397401052346809,"ry":0,"rx":15.781250000000002}}}