# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.banker_idle.frame matches 17.. run scoreboard players set @s aj.banker_idle.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.banker_idle.frame
execute at @s run function animated_java:bremor/animations/banker_idle/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.banker_idle.frame 1