# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.lowerrightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerrightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.rightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.lowerleftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerleftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.leftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.tingle_pen] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_tingle_pen set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.rightarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.tingle_book] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_tingle_book set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.leftarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.tingles_pack] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_tingles_pack set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.tingles_ballon_small] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_tingles_ballon_small set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.tingles_ballon_big] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_tingles_ballon_big set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.tingle.node.torso] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso set from storage animated_java:gu out