# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.locators.locator merge value { px: 0, py: 0, pz: 0, ry: 0, rx: 0 }