# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '80a42e2dcd285e6d716f834c5e3f29ef77c525b76998aebca43dc206e96dc8eb'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack