# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '25d0371b1b045729fdb3cf5ddafe09c63178028304abcb74ec6715be55eb0f77'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack