# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '6ac900f1dac2e21027e52c9214bb63ba1cd19e133ad632073ef75cbf29977e35'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack