# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lowerrightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,0f,1.5f,0.1648f,0f,1.5f,0f,0.3977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.0607f,-1.0607f,0.5625f,0f,-1.0607f,-1.0607f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerleftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,0f,1.5f,0.1648f,0f,1.5f,0f,0.3977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.0607f,-1.0607f,0.5625f,0f,-1.0607f,-1.0607f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_tingle_pen) {transformation: [-0.75f,0f,0f,-0.1875f,0f,-1.4489f,-0.1941f,1.6184f,0f,-0.3882f,0.7244f,0.7682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.5f,0f,0f,-0.5625f,0f,0.3882f,-1.4489f,1.4681f,0f,-1.4489f,-0.3882f,0.2426f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_tingle_book) {transformation: [-0.5303f,0f,-0.5303f,0.4688f,-0.1373f,0.7244f,0.1373f,1.6782f,0.5123f,0.1941f,-0.5123f,1.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.3882f,-1.4489f,1.4681f,0f,-1.4489f,-0.3882f,0.2426f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,1.6492f,0f,0f,-1.5f,0.2912f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_tingles_pack) {transformation: [-0.75f,0f,0f,0f,0f,0.7244f,0.0971f,1.384f,0f,0.1941f,-0.3622f,-0.1681f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_tingles_ballon_small) {transformation: [-1.515f,0f,0f,0f,0f,-1.4634f,0.3921f,2.7068f,0f,0.3921f,1.4634f,-0.396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_tingles_ballon_big) {transformation: [-3f,0f,0f,0f,0f,-2.3544f,0.7765f,3.8606f,0f,0.6309f,2.8978f,-0.7177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4489f,0.3882f,0.5625f,0f,0.3882f,-1.4489f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"sounds":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}