# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '8c09e971572dac31cdca2ebadb2b63165a2fbdf0fe26cbcc663ee66866721337'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack