# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.576f,0f,0f,-1.5f,0.1239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4625f,-0.3332f,1.1245f,0f,-0.3332f,-1.4625f,-0.001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.576f,0f,0f,-1.5f,0.1239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4625f,-0.3332f,1.1245f,0f,-0.3332f,-1.4625f,-0.001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.066f,0.1128f,1.4943f,-0.427f,1.017f,1.0952f,-0.1276f,1.3148f,-1.1006f,1.0187f,-0.0283f,0.6901f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.066f,-0.1128f,-0.5625f,0.1276f,1.017f,-1.0952f,2.0398f,0.0283f,-1.1006f,-1.0187f,0.2019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,-0.0349f,-1.4996f,2.0398f,0f,-1.4996f,0.0349f,0.2019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2228f,0f,0f,-1.5f,0.2425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2228f,0f,0f,-1.5f,0.2425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1245f,0f,0.3247f,-1.4644f,-0.001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":2.9947391601601105e-17,"py":0.02614476976785296,"pz":-0.2445390101248102,"ry":0,"rx":12.5}}}