# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5741f,0f,0f,-1.5f,0.1354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4407f,-0.4176f,1.1144f,0f,-0.4176f,-1.4407f,-0.0213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5741f,0f,0f,-1.5f,0.1354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4407f,-0.4176f,1.1144f,0f,-0.4176f,-1.4407f,-0.0213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0725f,0.1088f,1.4943f,-0.4301f,1.0789f,1.0342f,-0.1276f,1.2775f,-1.0395f,1.081f,-0.0283f,0.6277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0725f,-0.1088f,-0.5625f,0.1276f,1.0789f,-1.0342f,2.0296f,0.0283f,-1.0395f,-1.081f,0.1816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.2691f,-1.4757f,2.0296f,0f,-1.4757f,-0.2691f,0.1816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2127f,0f,0f,-1.5f,0.2222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2127f,0f,0f,-1.5f,0.2222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1144f,0f,0.3247f,-1.4644f,-0.0213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.2423899573210195e-17,"py":0.016033658656741778,"pz":-0.2647612323470324,"ry":0,"rx":12.5}}}