# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.576f,0f,0f,-1.5f,0.1441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4306f,-0.4511f,1.1125f,0f,-0.4511f,-1.4306f,-0.025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.576f,0f,0f,-1.5f,0.1441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4306f,-0.4511f,1.1125f,0f,-0.4511f,-1.4306f,-0.025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.075f,0.1071f,1.4943f,-0.4313f,1.1027f,1.0088f,-0.1276f,1.2654f,-1.0141f,1.1049f,-0.0283f,0.6067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.075f,-0.1071f,-0.5625f,0.1276f,1.1027f,-1.0088f,2.0278f,0.0283f,-1.0141f,-1.1049f,0.1779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.3882f,-1.4489f,2.0278f,0f,-1.4489f,-0.3882f,0.1779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2108f,0f,0f,-1.5f,0.2185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2108f,0f,0f,-1.5f,0.2185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1125f,0f,0.3247f,-1.4644f,-0.025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.288110104489187e-17,"py":0.014166991990075095,"pz":-0.2684945656803658,"ry":0,"rx":12.5}}}