# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5746f,0f,0f,-1.5f,0.1389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4357f,-0.4344f,1.113f,0f,-0.4344f,-1.4357f,-0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5746f,0f,0f,-1.5f,0.1389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4357f,-0.4344f,1.113f,0f,-0.4344f,-1.4357f,-0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0737f,0.108f,1.4943f,-0.4307f,1.0909f,1.0216f,-0.1276f,1.271f,-1.0269f,1.093f,-0.0283f,0.6164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0737f,-0.108f,-0.5625f,0.1276f,1.0909f,-1.0216f,2.0283f,0.0283f,-1.0269f,-1.093f,0.1789f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.3289f,-1.4635f,2.0283f,0f,-1.4635f,-0.3289f,0.1789f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2113f,0f,0f,-1.5f,0.2195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2113f,0f,0f,-1.5f,0.2195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.113f,0f,0.3247f,-1.4644f,-0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.27559149276457e-17,"py":0.014678103101186224,"pz":-0.2674723434581435,"ry":0,"rx":12.5}}}