# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5761f,0f,0f,-1.5f,0.1257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4606f,-0.3417f,1.1238f,0f,-0.3417f,-1.4606f,-0.0025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5761f,0f,0f,-1.5f,0.1257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4606f,-0.3417f,1.1238f,0f,-0.3417f,-1.4606f,-0.0025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0667f,0.1125f,1.4943f,-0.4273f,1.0233f,1.0893f,-0.1276f,1.3113f,-1.0947f,1.0251f,-0.0283f,0.6845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0667f,-0.1125f,-0.5625f,0.1276f,1.0233f,-1.0893f,2.039f,0.0283f,-1.0947f,-1.0251f,0.2004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,-0.0044f,-1.5f,2.039f,0f,-1.5f,0.0044f,0.2004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2221f,0f,0f,-1.5f,0.241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2221f,0f,0f,-1.5f,0.241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1238f,0f,0.3247f,-1.4644f,-0.0025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.012156359081317e-17,"py":0.02543365865674163,"pz":-0.24596123234703243,"ry":0,"rx":12.5}}}