# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5741f,0f,0f,-1.5f,0.134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4431f,-0.4093f,1.1153f,0f,-0.4093f,-1.4431f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5741f,0f,0f,-1.5f,0.134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4431f,-0.4093f,1.1153f,0f,-0.4093f,-1.4431f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0718f,0.1092f,1.4943f,-0.4298f,1.0729f,1.0405f,-0.1276f,1.281f,-1.0458f,1.0749f,-0.0283f,0.6338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0718f,-0.1092f,-0.5625f,0.1276f,1.0729f,-1.0405f,2.0306f,0.0283f,-1.0458f,-1.0749f,0.1835f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.239f,-1.4808f,2.0306f,0f,-1.4808f,-0.239f,0.1835f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2136f,0f,0f,-1.5f,0.2241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2136f,0f,0f,-1.5f,0.2241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1153f,0f,0.3247f,-1.4644f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.2200741712032233e-17,"py":0.016944769767852863,"pz":-0.2629390101248102,"ry":0,"rx":12.5}}}