# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5743f,0f,0f,-1.5f,0.1329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4454f,-0.4009f,1.1163f,0f,-0.4009f,-1.4454f,-0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5743f,0f,0f,-1.5f,0.1329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4454f,-0.4009f,1.1163f,0f,-0.4009f,-1.4454f,-0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0712f,0.1096f,1.4943f,-0.4295f,1.0668f,1.0467f,-0.1276f,1.2847f,-1.052f,1.0688f,-0.0283f,0.6401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0712f,-0.1096f,-0.5625f,0.1276f,1.0668f,-1.0467f,2.0316f,0.0283f,-1.052f,-1.0688f,0.1855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.2088f,-1.4854f,2.0316f,0f,-1.4854f,-0.2088f,0.1855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2146f,0f,0f,-1.5f,0.2261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2146f,0f,0f,-1.5f,0.2261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1163f,0f,0.3247f,-1.4644f,-0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.195036947753988e-17,"py":0.01796699199007512,"pz":-0.26089456568036573,"ry":0,"rx":12.5}}}