# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5748f,0f,0f,-1.5f,0.1311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.45f,-0.384f,1.1185f,0f,-0.384f,-1.45f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5748f,0f,0f,-1.5f,0.1311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.45f,-0.384f,1.1185f,0f,-0.384f,-1.45f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0699f,0.1105f,1.4943f,-0.4289f,1.0546f,1.059f,-0.1276f,1.2923f,-1.0644f,1.0565f,-0.0283f,0.6531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0699f,-0.1105f,-0.5625f,0.1276f,1.0546f,-1.059f,2.0338f,0.0283f,-1.0644f,-1.0565f,0.19f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.1481f,-1.4927f,2.0338f,0f,-1.4927f,-0.1481f,0.19f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2169f,0f,0f,-1.5f,0.2306f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2169f,0f,0f,-1.5f,0.2306f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1185f,0f,0.3247f,-1.4644f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.1400639136589297e-17,"py":0.020211436434519392,"pz":-0.25640567679147686,"ry":0,"rx":12.5}}}