# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5757f,0f,0f,-1.5f,0.1283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4565f,-0.3586f,1.1219f,0f,-0.3586f,-1.4565f,-0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5757f,0f,0f,-1.5f,0.1283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4565f,-0.3586f,1.1219f,0f,-0.3586f,-1.4565f,-0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.068f,0.1117f,1.4943f,-0.4279f,1.0359f,1.0773f,-0.1276f,1.3039f,-1.0827f,1.0378f,-0.0283f,0.6725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.068f,-0.1117f,-0.5625f,0.1276f,1.0359f,-1.0773f,2.0372f,0.0283f,-1.0827f,-1.0378f,0.1967f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.0567f,-1.4989f,2.0372f,0f,-1.4989f,-0.0567f,0.1967f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2202f,0f,0f,-1.5f,0.2373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2202f,0f,0f,-1.5f,0.2373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1219f,0f,0.3247f,-1.4644f,-0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.057604362516341e-17,"py":0.023578103101186132,"pz":-0.24967234345814354,"ry":0,"rx":12.5}}}