# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5759f,0f,0f,-1.5f,0.1271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4586f,-0.3502f,1.1229f,0f,-0.3502f,-1.4586f,-0.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5759f,0f,0f,-1.5f,0.1271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4586f,-0.3502f,1.1229f,0f,-0.3502f,-1.4586f,-0.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0673f,0.1121f,1.4943f,-0.4276f,1.0297f,1.0833f,-0.1276f,1.3076f,-1.0887f,1.0315f,-0.0283f,0.6786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0673f,-0.1121f,-0.5625f,0.1276f,1.0297f,-1.0833f,2.0382f,0.0283f,-1.0887f,-1.0315f,0.1987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.0262f,-1.4998f,2.0382f,0f,-1.4998f,-0.0262f,0.1987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2212f,0f,0f,-1.5f,0.2393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2212f,0f,0f,-1.5f,0.2393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1229f,0f,0.3247f,-1.4644f,-0.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.0333835702665375e-17,"py":0.02456699199007506,"pz":-0.24769456568036577,"ry":0,"rx":12.5}}}