# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5754f,0f,0f,-1.5f,0.1293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4544f,-0.3671f,1.1208f,0f,-0.3671f,-1.4544f,-0.0083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5754f,0f,0f,-1.5f,0.1293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4544f,-0.3671f,1.1208f,0f,-0.3671f,-1.4544f,-0.0083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0686f,0.1113f,1.4943f,-0.4282f,1.0422f,1.0712f,-0.1276f,1.3f,-1.0766f,1.0441f,-0.0283f,0.6661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0686f,-0.1113f,-0.5625f,0.1276f,1.0422f,-1.0712f,2.0361f,0.0283f,-1.0766f,-1.0441f,0.1946f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.0872f,-1.4975f,2.0361f,0f,-1.4975f,-0.0872f,0.1946f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2192f,0f,0f,-1.5f,0.2352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2192f,0f,0f,-1.5f,0.2352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1208f,0f,0.3247f,-1.4644f,-0.0083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.084002304631295e-17,"py":0.0225003253234084,"pz":-0.2518278990136991,"ry":0,"rx":12.5}}}