# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5751f,0f,0f,-1.5f,0.1302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4522f,-0.3756f,1.1197f,0f,-0.3756f,-1.4522f,-0.0106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5751f,0f,0f,-1.5f,0.1302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4522f,-0.3756f,1.1197f,0f,-0.3756f,-1.4522f,-0.0106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0693f,0.1109f,1.4943f,-0.4285f,1.0484f,1.0651f,-0.1276f,1.2961f,-1.0705f,1.0503f,-0.0283f,0.6597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0693f,-0.1109f,-0.5625f,0.1276f,1.0484f,-1.0651f,2.035f,0.0283f,-1.0705f,-1.0503f,0.1923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.1177f,-1.4954f,2.035f,0f,-1.4954f,-0.1177f,0.1923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.218f,0f,0f,-1.5f,0.2329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.218f,0f,0f,-1.5f,0.2329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1197f,0f,0.3247f,-1.4644f,-0.0106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.1117609654119683e-17,"py":0.02136699199007497,"pz":-0.25409456568036576,"ry":0,"rx":12.5}}}