# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5745f,0f,0f,-1.5f,0.132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4478f,-0.3924f,1.1174f,0f,-0.3924f,-1.4478f,-0.0152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5745f,0f,0f,-1.5f,0.132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4478f,-0.3924f,1.1174f,0f,-0.3924f,-1.4478f,-0.0152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0.0706f,0.1101f,1.4943f,-0.4292f,1.0607f,1.0529f,-0.1276f,1.2885f,-1.0582f,1.0627f,-0.0283f,0.6466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0706f,-0.1101f,-0.5625f,0.1276f,1.0607f,-1.0529f,2.0327f,0.0283f,-1.0582f,-1.0627f,0.1877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,0.1785f,-1.4893f,2.0327f,0f,-1.4893f,-0.1785f,0.1877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2157f,0f,0f,-1.5f,0.2283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2157f,0f,0f,-1.5f,0.2283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.1174f,0f,0.3247f,-1.4644f,-0.0152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":3.168094718172747e-17,"py":0.019066991990075,"pz":-0.25869456568036575,"ry":0,"rx":12.5}}}