# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_chest_layer2) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.125f,0f,0.3247f,-1.4644f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerrightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5758f,0f,0f,-1.5f,0.1217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upperrightleg_layer2) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4644f,-0.3247f,1.125f,0f,-0.3247f,-1.4644f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.4644f,-0.3247f,1.125f,0f,-0.3247f,-1.4644f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerleftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5758f,0f,0f,-1.5f,0.1217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upperleftleg_layer2) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4644f,-0.3247f,1.125f,0f,-0.3247f,-1.4644f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.4644f,-0.3247f,1.125f,0f,-0.3247f,-1.4644f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_spear) {transformation: [0.0654f,0.1132f,1.4943f,-0.4266f,1.0106f,1.1011f,-0.1276f,1.3182f,-1.1065f,1.0123f,-0.0283f,0.6953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.4943f,0.0654f,-0.1132f,-0.5625f,0.1276f,1.0106f,-1.1011f,2.0403f,0.0283f,-1.1065f,-1.0123f,0.2029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,-0.0654f,-1.4986f,2.0403f,0f,-1.4986f,0.0654f,0.2029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head_layer2) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2233f,0f,0f,-1.5f,0.2435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,2.2233f,0f,0f,-1.5f,0.2435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.4644f,0.3247f,1.125f,0f,0.3247f,-1.4644f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}