# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:south_gate_soldier/animations/banker_idle/zzz/apply_frame {frame: 16}
scoreboard players add @s aj.banker_idle.frame 1