# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/bomber_block/zzz/apply_frame {frame: 10}
scoreboard players add @s aj.bomber_block.frame 1