# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/pause_all
tag @s add aj.tingle.animation.banker_dance.playing
scoreboard players set @s aj.banker_dance.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:tingle/animations/banker_dance/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only