# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mack/animations/banker_pound/zzz/apply_frame {frame: 24}
scoreboard players add @s aj.banker_pound.frame 1