# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:happy_mask_salesman/animations/pause_all
tag @s add aj.happy_mask_salesman.animation.happy_mask_introduction_7.playing
scoreboard players set @s aj.happy_mask_introduction_7.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:happy_mask_salesman/animations/happy_mask_introduction_7/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only