# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'd7736eacb748217fd00516b457bdb90c7c204670c302c69b95de3ba66b3d46c4'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack