# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'd7537bbf021c34b7ea51b1aa29d613f4955c9179187df5d68f82d5d691dcf7e4'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack