# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '0885d5f9a21b56da22444ec5cbf265d3389c6e2ed014c3de222e004c70db243e'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack