# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mack.root] run return 0
execute if entity @s[tag=aj.mack.animation.carpenter_wave_up.playing] run function animated_java:mack/animations/carpenter_wave_up/zzz/on_tick
execute if entity @s[tag=aj.mack.animation.carpenter_shout_up.playing] run function animated_java:mack/animations/carpenter_shout_up/zzz/on_tick
execute on passengers run rotate @s ~ ~