# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/bomber_sit/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.bomber_sit.frame 1