# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:greatfairy_clocktown/animations/pause_all
scoreboard players set @s aj.greatfairy_appear.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:greatfairy_clocktown/animations/greatfairy_appear/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only