# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.greatfairy_float2reach.frame matches 31.. run scoreboard players set @s aj.greatfairy_float2reach.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.greatfairy_float2reach.frame
execute at @s run function animated_java:greatfairy_clocktown/animations/greatfairy_float2reach/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.greatfairy_float2reach.frame 1