# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:west_gate_soldier rig_hash set value '15b15e18069365d879017507f345d5fa161120f287bc14b1b2f5a2d172dc1e0f'
scoreboard objectives add aj.guard_idle.frame dummy
scoreboard objectives add aj.guard_idle_day3.frame dummy
scoreboard objectives add aj.guard_block.frame dummy
scoreboard objectives add aj.guard_move.frame dummy