# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/tingle_fall/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.tingle_fall.frame 1