# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp args
$execute store result storage animated_java:temp args.frame int 1 run scoreboard players set @s aj.greatfairy_appear2float.frame $(frame)
execute at @s run function animated_java:greatfairy_clocktown/animations/greatfairy_appear2float/zzz/set_frame with storage animated_java:temp args