# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:great_clocktown rig_hash set value 'b093641e9729a296a157dbf056b1fa0836897c69dd4c9068a61b33835e3d9cc1'
scoreboard objectives add aj.great_appear.frame dummy
scoreboard objectives add aj.great_appear2float.frame dummy
scoreboard objectives add aj.great_float.frame dummy
scoreboard objectives add aj.great_float2reach.frame dummy
scoreboard objectives add aj.great_reach.frame dummy
scoreboard objectives add aj.great_reach2float.frame dummy
scoreboard objectives add aj.great_float2disappear.frame dummy
scoreboard objectives add aj.great_disappear.frame dummy