# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.greatfairy_appear.frame
scoreboard objectives remove aj.greatfairy_appear2float.frame
scoreboard objectives remove aj.greatfairy_float.frame
scoreboard objectives remove aj.greatfairy_float2reach.frame
scoreboard objectives remove aj.greatfairy_reach.frame
scoreboard objectives remove aj.greatfairy_reach2float.frame
scoreboard objectives remove aj.greatfairy_float2disappear.frame
scoreboard objectives remove aj.greatfairy_disappear.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:greatfairy_clocktown)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'greatfairy_clocktown'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']