# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jugglers.root] run return 0
execute if entity @s[tag=aj.jugglers.animation.jugglers_idle.playing] run function animated_java:jugglers/animations/jugglers_idle/zzz/on_tick
execute on passengers run rotate @s ~ ~