# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b093641e9729a296a157dbf056b1fa0836897c69dd4c9068a61b33835e3d9cc1'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack