# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1.1989f,0.0523f,0f,-0.1696f,0.0654f,1.4986f,0f,0.563f,0f,0f,-1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.1989f,0.0523f,0f,-0.15f,0.0654f,1.4986f,0f,1.125f,0f,0f,-1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1.1989f,-0.0523f,0f,0.1696f,-0.0654f,1.4986f,0f,0.563f,0f,0f,-1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.1989f,-0.0523f,0f,0.15f,-0.0654f,1.4986f,0f,1.125f,0f,0f,-1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.2f,0f,0f,-0.45f,0f,1.5f,0f,2.0625f,0f,0f,-1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.2f,0f,0f,0.45f,0f,1.5f,0f,2.0625f,0f,0f,-1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1.2f,0f,0f,0f,0f,1.299f,-0.75f,2.25f,0f,-0.6f,-1.0392f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.2f,0f,0f,0f,0f,1.299f,-0.75f,2.25f,0f,-0.6f,-1.0392f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.2f,0f,0f,0f,0f,1.5f,0f,1.125f,0f,0f,-1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}