# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.lowerrightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerrightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.rightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.lowerleftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerleftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.leftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.rightarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.leftarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.torso] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.lowerrightleg1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerrightleg1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.rightleg1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightleg1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.lowerleftleg1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lowerleftleg1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.leftleg1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftleg1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.rightarm1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightarm1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.leftarm1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftarm1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.head1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.torso2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.red_ball1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_red_ball1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.red_ball2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_red_ball2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.yellow_ball1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_yellow_ball1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.yellow_ball2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_yellow_ball2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.blue_ball1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_blue_ball1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.blue_ball2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_blue_ball2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.blue_ball3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_blue_ball3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.jugglers.node.blue_ball4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_blue_ball4 set from storage animated_java:gu out