# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:apprentice/animations/banker_wave/zzz/apply_frame {frame: 16}
scoreboard players add @s aj.banker_wave.frame 1