# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:happy_mask_salesman rig_hash set value 'd5c17daad17bca620d4c098a70cb8dde9eaae65bf8b5a70f0b82cceeadd257bf'
scoreboard objectives add aj.happy_mask_idle_heavy.frame dummy
scoreboard objectives add aj.happy_mask_introduction_1.frame dummy
scoreboard objectives add aj.happy_mask_introduction_2.frame dummy
scoreboard objectives add aj.happy_mask_introduction_3_6_8.frame dummy
scoreboard objectives add aj.happy_mask_introduction_4.frame dummy
scoreboard objectives add aj.happy_mask_introduction_5.frame dummy
scoreboard objectives add aj.happy_mask_introduction_7.frame dummy