# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.happy_mask_idle_heavy.frame
scoreboard objectives remove aj.happy_mask_introduction_1.frame
scoreboard objectives remove aj.happy_mask_introduction_2.frame
scoreboard objectives remove aj.happy_mask_introduction_3_6_8.frame
scoreboard objectives remove aj.happy_mask_introduction_4.frame
scoreboard objectives remove aj.happy_mask_introduction_5.frame
scoreboard objectives remove aj.happy_mask_introduction_7.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:happy_mask_salesman)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'happy_mask_salesman'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']