# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.greatfairy_float2disappear.frame matches 11.. run scoreboard players set @s aj.greatfairy_float2disappear.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.greatfairy_float2disappear.frame
execute at @s run function animated_java:greatfairy_clocktown/animations/greatfairy_float2disappear/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.greatfairy_float2disappear.frame 1