# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:east_gate_soldier rig_hash set value '49fcae35d4bdcdd27eb5161508e7a629893badfa64ff85b9209f1a8c12774abb'
scoreboard objectives add aj.guard_idle.frame dummy
scoreboard objectives add aj.guard_idle_day3.frame dummy
scoreboard objectives add aj.guard_block.frame dummy
scoreboard objectives add aj.guard_move.frame dummy