# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.south_gate_soldier.root] run return 0
execute if entity @s[tag=aj.south_gate_soldier.animation.banker_idle.playing] run function animated_java:south_gate_soldier/animations/banker_idle/zzz/on_tick
execute if entity @s[tag=aj.south_gate_soldier.animation.banker_wave.playing] run function animated_java:south_gate_soldier/animations/banker_wave/zzz/on_tick
execute if entity @s[tag=aj.south_gate_soldier.animation.banker_pound.playing] run function animated_java:south_gate_soldier/animations/banker_pound/zzz/on_tick
execute if entity @s[tag=aj.south_gate_soldier.animation.banker_dance.playing] run function animated_java:south_gate_soldier/animations/banker_dance/zzz/on_tick
execute if entity @s[tag=aj.south_gate_soldier.animation.default.playing] run function animated_java:south_gate_soldier/animations/default/zzz/on_tick
execute if entity @s[tag=aj.south_gate_soldier.animation.soldier_idle.playing] run function animated_java:south_gate_soldier/animations/soldier_idle/zzz/on_tick
execute if entity @s[tag=aj.south_gate_soldier.animation.soldier_block.playing] run function animated_java:south_gate_soldier/animations/soldier_block/zzz/on_tick
execute if entity @s[tag=aj.south_gate_soldier.animation.soldier_move.playing] run function animated_java:south_gate_soldier/animations/soldier_move/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:south_gate_soldier/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~