# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:happy_mask_salesman/animations/happy_mask_introduction_7/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.happy_mask_introduction_7.frame 1