# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/tingle_float/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.tingle_float.frame 1