# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '49fcae35d4bdcdd27eb5161508e7a629893badfa64ff85b9209f1a8c12774abb'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack