# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mack/animations/carpenter_shout_up/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.carpenter_shout_up.frame 1