# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.happy_mask_salesman.root] run return 0
execute if entity @s[tag=aj.happy_mask_salesman.animation.happy_mask_idle_heavy.playing] run function animated_java:happy_mask_salesman/animations/happy_mask_idle_heavy/zzz/on_tick
execute if entity @s[tag=aj.happy_mask_salesman.animation.happy_mask_introduction_1.playing] run function animated_java:happy_mask_salesman/animations/happy_mask_introduction_1/zzz/on_tick
execute if entity @s[tag=aj.happy_mask_salesman.animation.happy_mask_introduction_2.playing] run function animated_java:happy_mask_salesman/animations/happy_mask_introduction_2/zzz/on_tick
execute if entity @s[tag=aj.happy_mask_salesman.animation.happy_mask_introduction_3_6_8.playing] run function animated_java:happy_mask_salesman/animations/happy_mask_introduction_3_6_8/zzz/on_tick
execute if entity @s[tag=aj.happy_mask_salesman.animation.happy_mask_introduction_4.playing] run function animated_java:happy_mask_salesman/animations/happy_mask_introduction_4/zzz/on_tick
execute if entity @s[tag=aj.happy_mask_salesman.animation.happy_mask_introduction_5.playing] run function animated_java:happy_mask_salesman/animations/happy_mask_introduction_5/zzz/on_tick
execute if entity @s[tag=aj.happy_mask_salesman.animation.happy_mask_introduction_7.playing] run function animated_java:happy_mask_salesman/animations/happy_mask_introduction_7/zzz/on_tick
execute on passengers run rotate @s ~ ~