# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:greatfairy_clocktown/animations/pause_all
tag @s add aj.greatfairy_clocktown.animation.greatfairy_reach.playing
scoreboard players set @s aj.greatfairy_reach.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:greatfairy_clocktown/animations/greatfairy_reach/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only