# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.tingle_inflate.frame matches 81.. run scoreboard players set @s aj.tingle_inflate.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.tingle_inflate.frame
execute at @s run function animated_java:tingle/animations/tingle_inflate/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.tingle_inflate.frame 1