# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp args
$execute store result storage animated_java:temp args.frame int 1 run scoreboard players set @s aj.happy_mask_idle_heavy.frame $(frame)
execute at @s run function animated_java:happy_mask_salesman/animations/happy_mask_idle_heavy/zzz/apply_frame with storage animated_java:temp args