# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.guard_idle.frame matches 41.. run scoreboard players set @s aj.guard_idle.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.guard_idle.frame
execute at @s run function animated_java:north_gate_soldier/animations/guard_idle/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.guard_idle.frame 1