# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:north_gate_soldier rig_hash set value 'ccd98c4ff01bce48a3221ebfe915687adb53dfe91aa4f3b6d0164e5c70888643'
scoreboard objectives add aj.guard_idle.frame dummy
scoreboard objectives add aj.guard_idle_day3.frame dummy
scoreboard objectives add aj.guard_block.frame dummy
scoreboard objectives add aj.guard_move.frame dummy