# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from entity @s data.locators.sounds
function animated_java:tingle/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args