# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.global.data] run function animated_java:greatfairy_clocktown/animations/greatfairy_float2reach/zzz/frames/$(frame) with entity @s data.uuids_by_name
return 1