# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:greatfairy_clocktown/animations/greatfairy_float2reach/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.greatfairy_float2reach.frame 1