# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b91b1167b08f482614f76480bc0f2a8e690cff48e6a13452abbf19c4913bb8b5'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack