# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.greatfairy_reach2float.frame matches 31.. run scoreboard players set @s aj.greatfairy_reach2float.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.greatfairy_reach2float.frame
execute at @s run function animated_java:greatfairy_clocktown/animations/greatfairy_reach2float/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.greatfairy_reach2float.frame 1