# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.mack.node.lower_rightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lower_rightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.mack.node.rightleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.mack.node.lower_leftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lower_leftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.mack.node.leftleg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftleg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.mack.node.rightarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.mack.node.leftarm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftarm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.mack.node.hat] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hat set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.mack.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.mack.node.torso] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso set from storage animated_java:gu out