# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:south_gate_soldier/animations/pause_all
tag @s add aj.south_gate_soldier.animation.guard_idle_day3.playing
scoreboard players set @s aj.guard_idle_day3.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:south_gate_soldier/animations/guard_idle_day3/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only