# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:apprentice/animations/apprentice_stare_up/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.apprentice_stare_up.frame 1