# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:brac/animations/carpenter_wave_up/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.carpenter_wave_up.frame 1