# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.carpenter_wave_up.frame matches 21.. run scoreboard players set @s aj.carpenter_wave_up.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.carpenter_wave_up.frame
execute at @s run function animated_java:bremor/animations/carpenter_wave_up/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.carpenter_wave_up.frame 1