# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:greatfairy_clocktown/animations/greatfairy_float2disappear/zzz/apply_frame {frame: 10}
scoreboard players add @s aj.greatfairy_float2disappear.frame 1