# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.guard_move.frame matches 7.. run scoreboard players set @s aj.guard_move.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.guard_move.frame
execute at @s run function animated_java:tingle/animations/guard_move/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.guard_move.frame 1