# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.east_gate_soldier.root] run return 0
execute if entity @s[tag=aj.east_gate_soldier.animation.guard_idle.playing] run function animated_java:east_gate_soldier/animations/guard_idle/zzz/on_tick
execute if entity @s[tag=aj.east_gate_soldier.animation.guard_idle_day3.playing] run function animated_java:east_gate_soldier/animations/guard_idle_day3/zzz/on_tick
execute if entity @s[tag=aj.east_gate_soldier.animation.guard_block.playing] run function animated_java:east_gate_soldier/animations/guard_block/zzz/on_tick
execute if entity @s[tag=aj.east_gate_soldier.animation.guard_move.playing] run function animated_java:east_gate_soldier/animations/guard_move/zzz/on_tick
execute on passengers run rotate @s ~ ~