# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.bremor.root] run return 0
execute if entity @s[tag=aj.bremor.animation.carpenter_carry_plank.playing] run function animated_java:bremor/animations/carpenter_carry_plank/zzz/on_tick
execute on passengers run rotate @s ~ ~