# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.guard_block.frame matches 31.. run scoreboard players set @s aj.guard_block.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.guard_block.frame
execute at @s run function animated_java:west_gate_soldier/animations/guard_block/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.guard_block.frame 1