# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.tingle.animation.tingle_float.playing] run function animated_java:tingle/animations/tingle_float/zzz/on_tick
execute if entity @s[tag=aj.tingle.animation.tingle_idle.playing] run function animated_java:tingle/animations/tingle_idle/zzz/on_tick
execute if entity @s[tag=aj.tingle.animation.tingle_idle_kick.playing] run function animated_java:tingle/animations/tingle_idle_kick/zzz/on_tick
execute if entity @s[tag=aj.tingle.animation.tingle_idle_spin.playing] run function animated_java:tingle/animations/tingle_idle_spin/zzz/on_tick
execute if entity @s[tag=aj.tingle.animation.tingle_inflate.playing] run function animated_java:tingle/animations/tingle_inflate/zzz/on_tick
execute if entity @s[tag=aj.tingle.animation.tingle_limpah.playing] run function animated_java:tingle/animations/tingle_limpah/zzz/on_tick
execute if entity @s[tag=aj.tingle.animation.tingle_pop.playing] run function animated_java:tingle/animations/tingle_pop/zzz/on_tick
execute if entity @s[tag=aj.tingle.animation.tingle_fall.playing] run function animated_java:tingle/animations/tingle_fall/zzz/on_tick
execute if entity @s[tag=aj.tingle.animation.tingle_land.playing] run function animated_java:tingle/animations/tingle_land/zzz/on_tick