# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:tingle rig_hash set value '80a42e2dcd285e6d716f834c5e3f29ef77c525b76998aebca43dc206e96dc8eb'
scoreboard objectives add aj.tingle_float.frame dummy
scoreboard objectives add aj.tingle_idle.frame dummy
scoreboard objectives add aj.tingle_idle_kick.frame dummy
scoreboard objectives add aj.tingle_idle_spin.frame dummy
scoreboard objectives add aj.tingle_inflate.frame dummy
scoreboard objectives add aj.tingle_limpah.frame dummy
scoreboard objectives add aj.tingle_pop.frame dummy
scoreboard objectives add aj.tingle_fall.frame dummy
scoreboard objectives add aj.tingle_land.frame dummy