# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:tingle rig_hash set value '25d0371b1b045729fdb3cf5ddafe09c63178028304abcb74ec6715be55eb0f77'
scoreboard objectives add aj.tingle_float.frame dummy
scoreboard objectives add aj.tingle_idle.frame dummy
scoreboard objectives add aj.tingle_idle_kick.frame dummy
scoreboard objectives add aj.tingle_idle_spin.frame dummy
scoreboard objectives add aj.tingle_inflate.frame dummy
scoreboard objectives add aj.tingle_limpah.frame dummy
scoreboard objectives add aj.tingle_pop.frame dummy
scoreboard objectives add aj.tingle_fall.frame dummy
scoreboard objectives add aj.tingle_land.frame dummy