# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.tingle_float.frame
scoreboard objectives remove aj.tingle_idle.frame
scoreboard objectives remove aj.tingle_idle_kick.frame
scoreboard objectives remove aj.tingle_idle_spin.frame
scoreboard objectives remove aj.tingle_inflate.frame
scoreboard objectives remove aj.tingle_limpah.frame
scoreboard objectives remove aj.tingle_pop.frame
scoreboard objectives remove aj.tingle_fall.frame
scoreboard objectives remove aj.tingle_land.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:tingle)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'tingle'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']