# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.tingle.node.lowerrightleg] run data merge entity @s { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.rightleg] run data merge entity @s { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.lowerleftleg] run data merge entity @s { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.leftleg] run data merge entity @s { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.tingle_pen] run data merge entity @s { transformation: [-0.5f,0f,0f,-0.125f,0f,0f,-0.5f,1.0625f,0f,-1f,0f,0.1875f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.misc_right_items] run data merge entity @s { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.rightarm] run data merge entity @s { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.tingle_book] run data merge entity @s { transformation: [-0.3536f,0f,-0.3536f,0.3125f,-0.3536f,0f,0.3536f,0.75f,0f,0.5f,0f,0.3125f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.misc_left_items] run data merge entity @s { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.leftarm] run data merge entity @s { transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.tingles_pack] run data merge entity @s { transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,1.25f,0f,0f,-0.25f,-0.25f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.tingles_ballon_small] run data merge entity @s { transformation: [-1.01f,0f,0f,0f,0f,-0.8747f,0.505f,2.0625f,0f,0.505f,0.8747f,-0.625f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.tingles_ballon_big] run data merge entity @s { transformation: [-2f,0f,0f,0f,0f,-1.4073f,1f,2.75f,0f,0.8125f,1.7321f,-1.0312f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.tingle] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,-0.25f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.backpack] run data merge entity @s { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.tingle.node.torso] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }