# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:happy_mask_salesman/animations/happy_mask_idle_heavy/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.happy_mask_idle_heavy.frame 1