# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '15b15e18069365d879017507f345d5fa161120f287bc14b1b2f5a2d172dc1e0f'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack