# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:south_gate_soldier rig_hash set value 'ee9ad9cf56c7f63f94a7689a04c7135e61c534e59fc8517c5e4a549e2390f7bb'
scoreboard objectives add aj.banker_idle.frame dummy
scoreboard objectives add aj.banker_wave.frame dummy
scoreboard objectives add aj.banker_pound.frame dummy
scoreboard objectives add aj.banker_dance.frame dummy
scoreboard objectives add aj.default.frame dummy
scoreboard objectives add aj.soldier_idle.frame dummy
scoreboard objectives add aj.soldier_block.frame dummy
scoreboard objectives add aj.soldier_move.frame dummy