# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:south_gate_soldier rig_hash set value '6f3ee83be75fbb62ca0569ba86b235ec90821fd329728edf87690ba77f72c298'
scoreboard objectives add aj.guard_idle.frame dummy
scoreboard objectives add aj.guard_idle_day3.frame dummy
scoreboard objectives add aj.guard_block.frame dummy
scoreboard objectives add aj.guard_move.frame dummy