# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.guard_idle.frame
scoreboard objectives remove aj.guard_idle_day3.frame
scoreboard objectives remove aj.guard_block.frame
scoreboard objectives remove aj.guard_move.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:south_gate_soldier)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'south_gate_soldier'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']