# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:south_gate_soldier/animations/banker_dance/zzz/apply_frame {frame: 24}
scoreboard players add @s aj.banker_dance.frame 1