# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.banker.root] run return 0
execute if entity @s[tag=aj.banker.animation.default.playing] run function animated_java:banker/animations/default/zzz/on_tick
execute if entity @s[tag=aj.banker.animation.idle.playing] run function animated_java:banker/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.banker.animation.wave.playing] run function animated_java:banker/animations/wave/zzz/on_tick
execute if entity @s[tag=aj.banker.animation.pound.playing] run function animated_java:banker/animations/pound/zzz/on_tick
execute if entity @s[tag=aj.banker.animation.dance.playing] run function animated_java:banker/animations/dance/zzz/on_tick
execute on passengers run rotate @s ~ ~