# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/tingle_idle_kick/zzz/apply_frame {frame: 50}
scoreboard players add @s aj.tingle_idle_kick.frame 1