# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:east_gate_soldier/animations/guard_idle_day3/zzz/apply_frame {frame: 10}
scoreboard players add @s aj.guard_idle_day3.frame 1