# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mack/animations/pause_all
tag @s add aj.mack.animation.guard_move.playing
scoreboard players set @s aj.guard_move.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:mack/animations/guard_move/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only