# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.brac.root] run return 0
execute if entity @s[tag=aj.brac.animation.carpenter_shout.playing] run function animated_java:brac/animations/carpenter_shout/zzz/on_tick
execute on passengers run rotate @s ~ ~