# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:jugglers/animations/jugglers_idle/zzz/apply_frame {frame: 192}
scoreboard players add @s aj.jugglers_idle.frame 1