# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.tingle_idle_spin.frame matches 25.. run scoreboard players set @s aj.tingle_idle_spin.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.tingle_idle_spin.frame
execute at @s run function animated_java:tingle/animations/tingle_idle_spin/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.tingle_idle_spin.frame 1