# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:mack rig_hash set value '4ee88d8158cf21934e4fc2df2f708ea55528b06ae0df02d54f279c44724b540e'
scoreboard objectives add aj.carpenter_wave_up.frame dummy
scoreboard objectives add aj.carpenter_shout_up.frame dummy