# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.banker_idle.frame
scoreboard objectives remove aj.banker_wave.frame
scoreboard objectives remove aj.banker_pound.frame
scoreboard objectives remove aj.banker_dance.frame
scoreboard objectives remove aj.default.frame
scoreboard objectives remove aj.apprentice_stare_up.frame
scoreboard objectives remove aj.carpenter_wave_up.frame
scoreboard objectives remove aj.carpenter_shout_up.frame
scoreboard objectives remove aj.carpenter_idle.frame
scoreboard objectives remove aj.guard_idle.frame
scoreboard objectives remove aj.guard_block.frame
scoreboard objectives remove aj.guard_move.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:mack)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'mack'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']