# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:stray_fairy_clocktown rig_hash set value 'b91b1167b08f482614f76480bc0f2a8e690cff48e6a13452abbf19c4913bb8b5'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.move.frame dummy
scoreboard objectives add aj.collected.frame dummy