# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:stray_fairy_clocktown/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.stray_fairy_clocktown.node.wings] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.6875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.stray_fairy_clocktown.node.body] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.stray_fairy_clocktown.node.model] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }