# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:happy_mask_salesman/animations/happy_mask_introduction_3_6_8/zzz/apply_frame {frame: 35}
scoreboard players add @s aj.happy_mask_introduction_3_6_8.frame 1