# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.greatfairy_clocktown.animation.greatfairy_appear.playing
tag @s remove aj.greatfairy_clocktown.animation.greatfairy_appear2float.playing
tag @s remove aj.greatfairy_clocktown.animation.greatfairy_float.playing
tag @s remove aj.greatfairy_clocktown.animation.greatfairy_float2reach.playing
tag @s remove aj.greatfairy_clocktown.animation.greatfairy_reach.playing
tag @s remove aj.greatfairy_clocktown.animation.greatfairy_reach2float.playing
tag @s remove aj.greatfairy_clocktown.animation.greatfairy_float2disappear.playing
tag @s remove aj.greatfairy_clocktown.animation.greatfairy_disappear.playing