# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:soldier/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.soldier.node.lower_rightleg] run data merge entity @s { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.soldier.node.rightleg] run data merge entity @s { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.soldier.node.lower_leftleg] run data merge entity @s { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.soldier.node.leftleg] run data merge entity @s { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.soldier.node.item_display] run data merge entity @s { transformation: [0f,0f,1f,-0.25f,1f,0f,0f,0.8125f,0f,1f,0f,-0.125f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.soldier.node.rightarm] run data merge entity @s { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.soldier.node.leftarm] run data merge entity @s { transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.soldier.node.hat] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.soldier.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.soldier.node.torso] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }