# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:soldier rig_hash set value 'f7685ce8a2425db20e0a0111fc2e5f8cb0ce1282b10e05a3290874150de6e4de'
scoreboard objectives add aj.banker_idle.frame dummy
scoreboard objectives add aj.banker_wave.frame dummy
scoreboard objectives add aj.banker_pound.frame dummy
scoreboard objectives add aj.banker_dance.frame dummy
scoreboard objectives add aj.default.frame dummy
scoreboard objectives add aj.guard_idle.frame dummy
scoreboard objectives add aj.guard_block.frame dummy
scoreboard objectives add aj.guard_move.frame dummy