# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/tingle_idle_spin/zzz/apply_frame {frame: 24}
scoreboard players add @s aj.tingle_idle_spin.frame 1