# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '1e0d79d0665db2afe0f8f7c48ac1190b83862efd2d4d2a8e41fd853d13832df3'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack