# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '847cf77dea7c219bda80727bfdee817c625fb85b3c5beca0abcbf5a18abcddf0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack