# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.apprentice.root] run return 0
execute if entity @s[tag=aj.apprentice.animation.apprentice_stare_up.playing] run function animated_java:apprentice/animations/apprentice_stare_up/zzz/on_tick
execute on passengers run rotate @s ~ ~