# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.apprentice.animation.banker_idle.playing] run function animated_java:apprentice/animations/banker_idle/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.banker_wave.playing] run function animated_java:apprentice/animations/banker_wave/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.banker_pound.playing] run function animated_java:apprentice/animations/banker_pound/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.banker_dance.playing] run function animated_java:apprentice/animations/banker_dance/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.default.playing] run function animated_java:apprentice/animations/default/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.apprentice_stare_up.playing] run function animated_java:apprentice/animations/apprentice_stare_up/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.carpenter_wave_up.playing] run function animated_java:apprentice/animations/carpenter_wave_up/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.carpenter_shout_up.playing] run function animated_java:apprentice/animations/carpenter_shout_up/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.carpenter_idle.playing] run function animated_java:apprentice/animations/carpenter_idle/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.guard_idle.playing] run function animated_java:apprentice/animations/guard_idle/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.guard_block.playing] run function animated_java:apprentice/animations/guard_block/zzz/on_tick
execute if entity @s[tag=aj.apprentice.animation.guard_move.playing] run function animated_java:apprentice/animations/guard_move/zzz/on_tick