# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:banker rig_hash set value '8c09e971572dac31cdca2ebadb2b63165a2fbdf0fe26cbcc663ee66866721337'
scoreboard objectives add aj.default.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.wave.frame dummy
scoreboard objectives add aj.pound.frame dummy
scoreboard objectives add aj.dance.frame dummy