# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f8e6058e3bd905d5257b5a992ba28ae98e64bcc13787197f1380784822fdb1b9'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack