# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:stray_fairy_clocktown/animations/pause_all
tag @s add aj.stray_fairy_clocktown.animation.move.playing
scoreboard players set @s aj.move.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:stray_fairy_clocktown/animations/move/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only