# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.global.data] run function animated_java:east_gate_soldier/animations/guard_block/zzz/frames/$(frame) with entity @s data.uuids_by_name
return 1