# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.tingle.animation.tingle_float.playing
tag @s remove aj.tingle.animation.tingle_idle.playing
tag @s remove aj.tingle.animation.tingle_idle_kick.playing
tag @s remove aj.tingle.animation.tingle_idle_spin.playing
tag @s remove aj.tingle.animation.tingle_inflate.playing
tag @s remove aj.tingle.animation.tingle_limpah.playing
tag @s remove aj.tingle.animation.tingle_pop.playing
tag @s remove aj.tingle.animation.tingle_fall.playing
tag @s remove aj.tingle.animation.tingle_land.playing