# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wings) {transformation: [1f,0f,0f,1.5f,0f,1f,0f,2.6875f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [1f,0f,0f,1.5f,0f,1f,0f,2f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^1.5 ^2.375 ^0 rotated ~180 ~0 run function animated_java:stray_fairy_clocktown/animations/collected/zzz/frames/0_locator_particles
data modify entity @s data merge value {"cameras":{},"locators":{"particles":{"px":1.5,"py":2.375,"pz":1.8369701987210297e-16,"ry":180,"rx":0}}}