# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wings) {transformation: [0f,0f,-0.5f,0f,0f,0.5f,0f,1.3438f,0.5f,0f,0f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,0f,-0.5f,0f,0f,0.5f,0f,1f,0.5f,0f,0f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^1.1875 ^0.75 rotated ~270 ~0 run function animated_java:stray_fairy_clocktown/animations/collected/zzz/frames/20_locator_particles
data modify entity @s data merge value {"cameras":{},"locators":{"particles":{"px":7.468494375772197e-17,"py":1.1875,"pz":0.7500000000000002,"ry":270,"rx":0}}}