# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wings) {transformation: [0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0.00000375 ^0 rotated ~360 ~0 run function animated_java:stray_fairy_clocktown/animations/collected/zzz/frames/40_locator_particles
data modify entity @s data merge value {"cameras":{},"locators":{"particles":{"px":0,"py":0.0000037500000000000005,"pz":0,"ry":360,"rx":0}}}