# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lower_rightleg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.3802f,0f,0f,-1f,0.0869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9572f,-0.2896f,0.7392f,0f,-0.2896f,-0.9572f,-0.0217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_leftleg) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.3802f,0f,0f,-1f,0.0869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1f,0f,0f,0.125f,0f,0.9572f,-0.2896f,0.7392f,0f,-0.2896f,-0.9572f,-0.0217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9962f,0.0492f,-0.072f,-0.375f,0.0851f,0.7273f,-0.6811f,1.3494f,0.0189f,-0.6846f,-0.7287f,0.1136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,0f,0f,0.375f,0f,0.2193f,-0.9757f,1.3494f,0f,-0.9757f,-0.2193f,0.1136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4714f,0f,0f,-1f,0.1407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4714f,0f,0f,-1f,0.1407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1f,0f,0f,0f,0f,0.9763f,0.2164f,0.7392f,0f,0.2164f,-0.9763f,-0.0217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}