# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:bremor/animations/pause_all
tag @s add aj.bremor.animation.guard_idle.playing
scoreboard players set @s aj.guard_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:bremor/animations/guard_idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only