# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_chest_layer2) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerrightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,0.5625f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upperrightleg_layer2) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.5f,0f,0f,-0.1875f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerleftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,0.5625f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upperleftleg_layer2) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.5f,0f,0f,0.1875f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_spear) {transformation: [0f,0f,1.5f,-0.375f,1.2287f,0.8604f,0f,1.2638f,-0.8604f,1.2287f,0f,0.3304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.5f,0f,0f,-0.5625f,0f,1.2287f,-0.8604f,2.0625f,0f,-0.8604f,-1.2287f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.75f,1.0038f,0.3362f,0.5625f,0.2256f,0.4065f,-1.3932f,2.0625f,-1.2793f,-0.5168f,-0.4428f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head_layer2) {transformation: [-1.5f,0f,0f,0f,0f,1.4489f,-0.3882f,2.25f,0f,-0.3882f,-1.4489f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.4489f,-0.3882f,2.25f,0f,-0.3882f,-1.4489f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}