# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tingle/animations/guru_guru_idle/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.guru_guru_idle.frame 1