# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:greatfairy_clocktown/animations/greatfairy_appear/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.greatfairy_appear.frame 1