# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:south_gate_soldier/animations/pause_all
tag @s add aj.south_gate_soldier.animation.banker_idle.playing
scoreboard players set @s aj.banker_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:south_gate_soldier/animations/banker_idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only