# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:apprentice rig_hash set value '1e0d79d0665db2afe0f8f7c48ac1190b83862efd2d4d2a8e41fd853d13832df3'
scoreboard objectives add aj.apprentice_stare_up.frame dummy