# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:bremor/animations/carpenter_idle/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.carpenter_idle.frame 1