# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:south_gate_soldier/animations/soldier_move/zzz/apply_frame {frame: 6}
scoreboard players add @s aj.soldier_move.frame 1