# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.mack.animation.banker_idle.playing
tag @s remove aj.mack.animation.banker_wave.playing
tag @s remove aj.mack.animation.banker_pound.playing
tag @s remove aj.mack.animation.banker_dance.playing
tag @s remove aj.mack.animation.default.playing
tag @s remove aj.mack.animation.apprentice_stare_up.playing
tag @s remove aj.mack.animation.carpenter_wave_up.playing
tag @s remove aj.mack.animation.carpenter_shout_up.playing
tag @s remove aj.mack.animation.carpenter_idle.playing
tag @s remove aj.mack.animation.guard_idle.playing
tag @s remove aj.mack.animation.guard_block.playing
tag @s remove aj.mack.animation.guard_move.playing