# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lowerrightleg) {transformation: [-1.4986f,0.0654f,0f,-0.212f,0.0654f,1.4986f,0f,0.563f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1.4986f,0.0654f,0f,-0.1875f,0.0654f,1.4986f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerleftleg) {transformation: [-1.4986f,-0.0654f,0f,0.212f,-0.0654f,1.4986f,0f,0.563f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1.4986f,-0.0654f,0f,0.1875f,-0.0654f,1.4986f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_plank) {transformation: [-0.2872f,-0.0001f,0.2411f,0.1466f,0.2265f,-1.5391f,0.2699f,2.3083f,0.0824f,4.2286f,0.0983f,0.0895f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1.149f,-0.9643f,0f,-0.5625f,0.9061f,-1.0797f,-0.513f,2.0625f,0.3298f,-0.393f,1.4095f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1.5f,0f,0f,0.5625f,0f,1.5f,0f,2.0625f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head_layer2) {transformation: [-1.5f,0f,0f,0f,0f,1.0607f,-1.0607f,2.25f,0f,-1.0607f,-1.0607f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.5f,0f,0f,0f,0f,1.0607f,-1.0607f,2.25f,0f,-1.0607f,-1.0607f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,1.125f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}